### ISSUE TITLE
DetachToken is null on client

### ISSUE THREAD

**Issue by vladnau89** [BoltEngine/Bolt-Tracker#179] opened 2020-11-30 16:08 UTC
### How to reproduce issue
1. import Example bolt package 
2. add /samples/AdvancedTutorial/scenes/MainMenu and /samples/AdvancedTutorial/scenes/Level1 scenes to BuildSettings
3. call Bolt/CompileAssembly
4. replace BoltNetwork.Destroy(entity.gameObject); to BoltNetwork.Destroy(entity.gameObject, new TestToken());  at 
 Assets/sample/AdvancedTutorial/scripts/Player.cs 63
5. add      public override void Detached()
		{
			Debug.LogError(entity.DetachToken);
		}
to Assets/sample/AdvancedTutorial/scripts/PlayerController.cs
6. Open Bolt Debug Start. add 2 client an push Build And Run
7. Look to the log concole on client when one of the client close app

### Expected Behavior
entity.DetachToken is not null on client

### Actual behavior
entity.DetachToken is null on client . but not null on server

### Configuration
- Unity Version: 2020.1.14f1
- Bolt Version: 1.2.14
- Operating System: Win10
- Network Configuration: Lan

**Comment by ramonmelo** [comment] 2020-12-01 19:58
Hello @vladnau89 ,

Thanks for your feedback. 

This was introduced in the last version, it will be fixed on the next release.

--
Ramon Melo
Photon Bolt Team

**Closed by ramonmelo** 2020-12-01 19:58 UTC
Labels: bug

**Comment by vladnau89** [comment] 2020-12-02 08:23
Is there a workaround?

**Comment by ramonmelo** [comment] 2020-12-02 11:29
Hello @vladnau89,

The new version is already out: https://assetstore.unity.com/packages/tools/network/photon-bolt-free-127156

--
Ramon Melo
Photon Bolt Team

**Comment by vladnau89** [comment] 2020-12-02 14:34
Unfortunately the issue is not fixed. steps to reproduce are the same. 

after update bolt to v1.2.14a version control system report that all files are not changed

**Comment by ramonmelo** [comment] 2020-12-02 15:15
Hello @vladnau89 ,

Can you check your update process? I just tested on a new project, and it's working as intended.
Take a look here: https://www.dropbox.com/s/7q6x1l5pbf0nsv0/bolt_entity_detach.mp4?dl=0

--
Ramon Melo
Photon Bolt Team

**Comment by vladnau89** [comment] 2020-12-02 15:35
Sorry! It was a bug with Unity Package Manager. The issue is fixed. Thank you!
