### ISSUE TITLE
BoltNetwork.get_IsSinglePlayer () gives NullReferenceException after Bolt Shutdown

### ISSUE THREAD

**Issue by paulo-lafeta** [BoltEngine/Bolt-Tracker#163] opened 2020-03-29 20:09 UTC
**Describe the bug**
Call to BoltNetwork.IsSinglePlayer is giving NullReferenceException after Photon Bolt is disconnected. 

"NullReferenceException: Object reference not set to an instance of an object
BoltNetwork.get_IsSinglePlayer ()"

This happens even though BoltNetwork.IsRunning returns as true. 

**To Reproduce**
1. Connect to Photon Bolt normally.
2. Shutdown Bolt with BoltNetwork.Shutdown();
3. Try to call BoltNetwork.IsSinglePlayer function.
4. See NullReferenceException occur. 

PS: BoltNetwork.IsRunning doesn't give NullRef after Bolt Shutdown.

**Expected behavior**
No NullReferenceException when calling BoltNetwork.IsSinglePlayer function.

**Actual behavior**
NullReferenceException when calling BoltNetwork.IsSinglePlayer function after Bolt Shutdown.

**Desktop:**
 - OS: Windows 10

**Additional context**
- Unity Version: 2019.3.7f1
- Bolt Version: 1.2.11

**Comment by ramonmelo** [comment] 2020-04-01 12:50
Hello @paulo-lafeta ,

I'm not entirely sure where or when you are checking the `BoltNetwork.IsSinglePlayer`, but I do not found any issue when running some tests based on your description. Maybe you can clarify with a reproduction sample? Which Bolt version are you using?

Here is the sample code I'm using the check your issue: [single_player_null_issue.unitypackage.zip](https://github.com/BoltEngine/Bolt-Tracker/files/4415153/single_player_null_issue.unitypackage.zip).

You will find in the zip a script that lets you start Bolt as a Server or in Single Player mode, and after it's running, you can call the Shutdown. On the `BoltShutdownBegin` callback, it's verified if Bolt is running and then check if it was running as Single Player. This step occurs before and after Bolt completes its shutdown procedure.

Before the shutdown completes, Bolt is still running, so it will log the `BoltNetwork.IsSinglePlayer`, after the shutdown, it will simply log `Bolt is not Running`.

**Comment by tkgszaluga** [comment] 2020-11-10 19:18
Hi Ramon,

I am seeing this error as well. Looks like the shutdown is asynchronous and at some point some UdpSocket becomes null, even though Bolt's IsRunning property still reports true.
I am able to reproduce it fairly easily with our debug gui. We're printing something like this from withinOnGui() (every frame):
GUILayout.Label($"IsSinglePlayer: {BoltNetwork.IsRunning && BoltNetwork.IsSinglePlayer}");
A workaround for this is:
GUILayout.Label($"IsSinglePlayer: {BoltNetwork.IsRunning &&  BoltNetwork.UdpSocket != null && BoltNetwork.IsSinglePlayer}");

**Comment by ramonmelo** [comment] 2020-11-10 19:47
Hello @tkgszaluga ,

Interesting, we will take a look.
Thanks for your feedback.

--
Ramon Melo
Photon Bolt Team

**Comment by ramonmelo** [comment] 2020-11-20 18:40
Thanks for your feedback,

Fixed on the next release.

The workaround from @tkgszaluga would work fine for now.

**Closed by ramonmelo** 2020-11-20 18:40 UTC
