### ISSUE TITLE
SetTransform inside Attached() causes entity to be teleported to (0,0,0) until first replication

### ISSUE THREAD

**Issue by TSchmGIT** [BoltEngine/Bolt-Tracker#5] opened 2016-03-23 14:29 UTC
###How to reproduce issue
1. Spawn an enemy via BoltNetwork.Instantiate() at a certain world pos different to (0,0,0)
2. Inside an entity behaviour use the Attached() callback to debug the position or just do Debug.Break() there.
3. When you add state.SetTransform(state.transform, transform); to the Attached() callback the entity will be teleported to (0,0,0) and you should see that in the editor

###Expected Behavior
The entity should be spawned at the given position for the client. Then the entity is not moved until the first replication arrives.

###Actual behavior
The entity spawns at the given position. Inside the same frame, probably due to "SetTransforms" the entity is set to (0,0,0) until the first replication update arrives.

###Configuration
Unity Version: 5.3.2f
Bolt Version: 0.4.3.11
Operating System: Windows 10 Version 1511 ( Build 10586.104 )
Network Configuration:

**Comment by karios** [comment] 2016-04-18 18:53
I second this issue. It's driving me crazy trying to find a workaround for this. Even worse, if interpolation is turned on, you also see the entity interpolating from (0,0,0) to the correct position when the first replication update arrives. And to add insult to injury, so does the rotation, from Quaternion.identity to correct.

**Comment by Fijit** [comment] 2016-04-26 15:26
I too am seeing this issue.

When spawning projectiles with a particle trail, all proxy versions of the projectile have a partial trail running from (0,0,0) to the spawn point of the projectile and then in the direction the projectile is actually supposed to be going.
The partial trail being a one frame lerp from origin to spawn position I guess.

**Comment by herpdederp** [comment] 2016-05-05 18:07
fixed in 0.4.3.14

**Closed by herpdederp** 2016-05-05 18:07 UTC

**Comment by karios** [comment] 2016-05-05 20:11
I still see this on 0.4.3.14

**Comment by herpdederp** [comment] 2016-05-05 21:16
@karios I can't reproduce this on 0.4.3.14, can you provide a repro?

**Comment by golex** [comment] 2016-05-06 04:57
Make sure you are using the new method for setting transforms, the obsolete method will still cause this issue.

**Comment by karios** [comment] 2016-05-06 13:44
Thanx. Can you elaborate on that please? Which one is the "new" method?

**Comment by herpdederp** [comment] 2016-05-06 15:43
@karios SetTransforms(state.transform, transform) for example

**Comment by vlab22** [comment] 2016-10-16 17:57
Not fixed for:
Bolt 0.4.3.16 (DEBUG)
Unity 5.4.1f1

Its works if you use:
```csharp
public override void Attached()
{
    state.SetTransforms(state.ShipTransform, transform);
}
```
@TSchmGIT ###Actual behavior if you use SetTransforms like this:
```csharp
public override void Attached()
{
	if (entity.isOwner)
	{
		state.SetTransforms(state.MyTransform, this.transform);
	}
	else
	{
		state.SetTransforms(state.MyTransform, _clientMyTransform);
		
		//_clientMyTransform is another Transform, not "this.transform"
	}
}
```
A workaround is to call a coroutine and in the "next" frame set the transform.position (server side) like this:
```csharp
public override void Attached()
{
	if (entity.isOwner)
	{
		state.SetTransforms(state.MyTransform, transform);

		StartCoroutine(ResendFirstPosition());
	}
	else
	{
		state.SetTransforms(state.MyTransform, _clientMyTransform);
		
		//_clientMyTransform is another Transform, not "this.transform"
	}
}

private IEnumerator ResendFirstPosition()
{
	yield return null;

	this.transform.position = this.transform.position + Vector3.forward * 0.00001f;
}
```
Is there a method or something to force update MyTransform state?
