### ISSUE TITLE
2018.3 Multiple errors when trying to install Bolt

### ISSUE THREAD

**Issue by buzzard2** [BoltEngine/Bolt-Tracker#99] opened 2018-12-16 17:27 UTC
### How to reproduce issue
1. Import Bolt asset
2. Bolt Wizard
3. Bolt Setup
4. install Core Package
5. Install Samples

### Expected Behavior
everything is smooth, no errors

### Actual behavior

**error 1**
IndexOutOfRangeException: Index was outside the bounds of the array.
BoltEditorUtilsInternal.CSharpIdentifier (System.String value) (at <d7d401968d534df195f911f66b053cfa>:0)
BoltCompiler.CompileMaps (BoltCompilerOperation op) (at <d7d401968d534df195f911f66b053cfa>:0)
BoltCompiler.Run (BoltCompilerOperation op) (at <d7d401968d534df195f911f66b053cfa>:0)
BoltUserAssemblyCompiler.Run () (at <d7d401968d534df195f911f66b053cfa>:0)
UnityEngine.Debug:LogException(Exception)
BoltLog:Exception(Exception)
BoltUserAssemblyCompiler:Run()
BoltMenuItems:RunCompiler()
BoltWizardWindow:InitialSetup() (at Assets/bolt/scripts/editor/BoltWizardWindowUtils.cs:276)
BoltWizardWindow:Install(BoltPackage) (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:883)
<>c__DisplayClass58_0:<DrawInstallOption>b__0() (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:759)
BoltWizardWindow:DrawStepOption(Texture2D, GUIContent, GUIContent, Nullable`1, Action, Action) (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:828)
BoltWizardWindow:DrawInstallOption(BoltInstalls) (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:776)
BoltWizardWindow:DrawSetupBolt() (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:461)
BoltWizardWindow:DrawContent() (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:426)
BoltWizardWindow:OnGUI() (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:402)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**error 2-4**
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name protobuf-net.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly path: {0}
UnityEditor.Scripting.ScriptCompilation.EditorBuildRules.CreateTargetAssemblies (System.Collections.Generic.IEnumerable`1[T] customScriptAssemblies, System.Collections.Generic.IEnumerable`1[T] precompiledAssemblies) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorBuildRules.cs:249)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.UpdateCustomTargetAssemblies () (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:619)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.SetAllCustomScriptAssemblyJsons (System.String[] paths) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:728)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.SetAllCustomScriptAssemblyJsons (System.String[] allAssemblyJsons) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:217)

**error 5**
CheckConsistency: GameObject does not reference component Light. Fixing.

### Configuration
- Unity Version: 2018.3.0f2
- Bolt Version: 1.2.4
- Operating System: Win10-x64

**Comment by Tykev** [comment] 2018-12-17 14:00
Error 1 is harmless and should happen only once upon importing Core package, fixed in next release.
Error 2-4 is caused by having two DLLs with same name in the project, in this case protobuf-net.dll. You can rename the one in ServerMonitor example to a protobuf-net-v2.dll. Fixed in next release.
Error 5 seems to be caused by the new prefab system (Explosion.prefab in Advanced Tutorial), saying you have Scene lighting disabled, thus you won't see changes made on Light component. Not sure why it's reported as error.

**Closed by Tykev** 2018-12-17 14:00 UTC
