### ISSUE TITLE
Issue trying to switch to debug mode

### ISSUE THREAD

**Issue by JosephFerano** [BoltEngine/Bolt-Tracker#98] opened 2018-12-10 19:56 UTC
### How to reproduce issue
1. Attempt to select `release` in `Bolt Settings` window

![screen](https://user-images.githubusercontent.com/2642263/49758346-2b1fba80-fc6b-11e8-8ace-10e187251892.png)

### Expected Behavior
DLLs should switch to release

### Actual behavior
An exception and both DLLs seem to remain in the root directory;

![image pasted at 2018-12-10 15-52](https://user-images.githubusercontent.com/2642263/49757821-d29bed80-fc69-11e8-8193-b6f6d830938f.png)

Here's the exception;

```
IOException: Win32 IO returned ERROR_ALREADY_EXISTS. Path: 
System.IO.File.Move (System.String sourceFileName, System.String destFileName) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
BoltSettingsWindow.SwitchDebugReleaseMode (System.Boolean debug) (at <5538509e9fe5428c844c59bc5dbbe674>:0)
BoltSettingsWindow+<>c__DisplayClass10_0.<Miscellaneous>b__0 () (at <5538509e9fe5428c844c59bc5dbbe674>:0)
BoltEditorGUI.WithLabel (System.String label, System.Action gui, System.Int32 labelMargin) (at <5538509e9fe5428c844c59bc5dbbe674>:0)
BoltSettingsWindow.Miscellaneous () (at <5538509e9fe5428c844c59bc5dbbe674>:0)
BoltSettingsWindow.OnGUI () (at <5538509e9fe5428c844c59bc5dbbe674>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /home/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at /home/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at /home/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:261)
UnityEditor.DockArea.OldOnGUI () (at /home/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:392)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, System.Boolean isComputingLayout) (at /home/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:238)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e) (at /home/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:376)
UnityEngine.Experimental.UIElements.EventDispatcher.DispatchEvent (UnityEngine.Experimental.UIElements.EventBase evt, UnityEngine.Experimental.UIElements.IPanel panel) (at /home/builduser/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:370)
UnityEngine.Experimental.UIElements.UIElementsUtility.DoDispatch (UnityEngine.Experimental.UIElements.BaseVisualElementPanel panel) (at /home/builduser/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:243)
UnityEngine.Experimental.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /home/builduser/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:74)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /home/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:171)
UnityEditor.PopupCallbackInfo:SetEnumValueDelegate(Object, String[], Int32)
```

### Configuration
- Unity Version: 2018.2.9f
- Bolt Version: 1.2.0.3
- Operating System: Reproduced on Windows 10 and Ubuntu 17.10
- Network Configuration: N/A

If there's a temp work around, please let me know.

**Comment by alexd-eps** [comment] 2018-12-11 11:18
Can workaround by restoring DLL's to their installed state, and then switching mode.
Issue caused by bolt moving / renaming the current DLL, which then fails on subsequent ops as the target already exists.

**Comment by ramonmelo** [comment] 2019-06-11 18:36
Thanks for the feedback.

Fixed on the next release.

**Closed by ramonmelo** 2019-06-11 18:36 UTC
Labels: bug
